FROM busybox
LABEL multi.label1="value1" \
      multi.label2="value2" \
      other="value3"
LABEL "com.example.vendor"="ACME Incorporated"
LABEL com.example.label-with-value="foo"
LABEL version="1.0"
LABEL description="This text illustrates \
that label-values can span multiple lines."
ENV ENV_VAR="123"
LABEL example="foo-$ENV_VAR"
