# syntax=docker/dockerfile:1
FROM alpine
WORKDIR user/src/app
# failed Unknown flag: keep-git-dir
#ADD --keep-git-dir=true https://github.com/KosarevDmitry/test.git buildkit/
# add ARG BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
# download  test.git file
ADD https://github.com/KosarevDmitry/test.git download/