@startuml
@startuml
:container is running;
:start;
note right
immediately  as  <color: red>  start-period <color: black>  default 0 sec
end note
repeat
:test;
 note right
 start each 5 sec as <color: red> start-interval <color:black> default 5 sec
 repeat during <color: red> interval <color:black> default 30 sec
end note
repeat while


repeat
  :test start ... completes or stop by timeout;
    if (timeout?) then (yes)
   :failer++;
   
     else (no)
  endif;
backward :wait;
note right
<color : red> interval<color : black>  default 30 sec
end note
repeat while (secuence failers == retries) is (No) not (Yes)
if (failer?) then (Yes)
 :Status: <color : red> unhealthy;
 
else  (No)
:Status: <color : green> healthy;
endif

stop


@enduml