# https://hub.docker.com/_/busybox
FROM busybox
ENV FOO=/bar
# WORKDIR /bar
WORKDIR ${FOO}   
# ADD . /bar
ADD . $FOO       
# COPY $FOO /quux
ENV MY_NAME="John Doe"
# with whiteaspace
ENV MY_DOG=Rex\ The\ Dog 
ENV MY_CAT=fluffy
# without equals sign
ENV MY_VAR my-value
#COPY /$FOO /quux 
# ENVs are visible in container
